#!/bin/bash -e

textBase='\033[0m'
textInformation='\033[1;34m'
textSuccess='\033[1;32m'

branchName=$(git rev-parse --abbrev-ref HEAD)
entradeTicketRegex='^[A-Z0-9]{2,8}-[0-9]{1,5}|merge|hotfix|release'

gitCommitMsg=$(head -n 1 "$1") # $1 is path = .git/COMMIT_EDITMSG

if [[ $gitCommitMsg =~ $entradeTicketRegex ]];then
  echo -e "$textInformation Already exist prefix branch-name, ignore appending prefix."
  echo -e "$textBase"
else
  echo -e "$textInformation Starting append prefix branch-name..."
  if [[ -n "$branchName" ]] && [[ $branchName =~ $entradeTicketRegex ]]; then
    # Append prefix branch name into commit message
    sed -i.bak -e "1s~^~$branchName ~" "$1"
    echo -e "$textSuccess Append prefix branch-name successfully."
    echo -e "$textBase"
  fi
fi
