#!/bin/bash -e

# regex to validate in commit msg
commit_regex='(^[A-Z0-9]{2,8}-[0-9]{1,5}|merge|hotfix|release)'
error_msg="Aborting commit. Your commit message must start with Jira/Clickup/Github code (eg: 'TML-123', 'ONEMIND-1111') or 'Merge'"

if ! grep -iqE "$commit_regex" "$1"; then
    echo "$error_msg" >&2
    exit 1
fi
