#!/bin/bash

textBase='\033[0m'
textInformation='\033[1;34m'
textSuccess='\033[1;32m'

echo "$textInformation \nStart lint code quality with rome"
bun run lint.check
echo "$textSuccess \nCheck rome format successfully."

# echo "$textInformation Start to check typings in projects"
# bun run lint:duplicate
# echo "$textSuccess Start to check typings in projects"

echo "$textBase"
